### ISSUE TITLE
Alt-Tab is not fully closed when cask is uninstalled and causes issues with system-wide shortcut use

### ISSUE THREAD

**Issue by dusrdev** [Homebrew/homebrew-cask#197173]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

When "brew upgrade -g" was used in a terminal that doesn't have app management permissions, some process of Alt-Tab remained running and was attempting to handle global shortcut events - causing entire system to become unresponsive until either event is manually canceled (escape/enter/power is pressed) or AltTab is killed via htop.

More details in AltTab repo - [](https://github.com/lwouis/alt-tab-macos/issues/4060)

Please ensure that all AltTab related processes are killed during update when the app is deleted.

### Command that failed

upgrade -g (partially)

### Output of command with `--verbose --debug`

```shell
NR
```

### Output of `brew doctor` and `brew config`

```shell
NR
```

### Output of `brew tap`

```shell
NR
```

**Comment by yunhao-jiang** [comment]
Had similar issue for v7.14.0 but seems to be cleared today when upgrading to v7.18.0
Does the issue still exist for you?

**Comment by dusrdev** [comment]
@yunhao-jiang I am not sure, since I am not upgrading to the same version multiple times, it is more difficult to test on my side.

But as long as you are aware of this and say it is fixed, you can close this issue.

If this occurs in the future, I can open another issue.

**Comment by yunhao-jiang** [comment]
@dusrdev Seems like the issue is not resolved and still causes issue, let me dig around and see what can be done.
Essentially it looks like when upgrading, the process won't quit and keeps running in the background. However when uninstalling, it will quit the app first.

**Comment by bevanjkay** [comment]
You can add `on_upgrade: :quit` to the `uninstall` stanza.

**Comment by yunhao-jiang** [comment]
Thanks, working on it now @bevanjkay
