### ISSUE TITLE
brew cask install google-chrome errors out with googlechrome.dmg was not quarantined properly

### ISSUE THREAD

**Issue by alexbigkid** [Homebrew/homebrew-cask#52128]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrewcask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue
cannot install google-chrome

#### Command that failed

```
brew cask install google-chrome
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
Already downloaded: /Users/abk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
==> Checking quarantine support
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/abk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/abk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
==> /Users/abk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg is not quarantined
==> Quarantining /Users/abk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/abk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg https://www.google.com/chrome/
==> Downloaded to -> /Users/abk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
==> Verifying SHA-256 checksum for Cask 'google-chrome'.
==> Installing Cask google-chrome
==> Cask::Installer#stage
hdiutil imageinfo /Users/abk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/abk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/ft/99qk4_9s0mb2pnhgbdt44_5c0000gn/T/d20180918-17591-1ojzgly /Users/abk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
find . -print0
mkbom -s -i /var/folders/ft/99qk4_9s0mb2pnhgbdt44_5c0000gn/T/20180918-17591-1dc1fur.list -- /var/folders/ft/99qk4_9s0mb2pnhgbdt44_5c0000gn/T/20180918-17591-23o4tm.bom
ditto --bom /var/folders/ft/99qk4_9s0mb2pnhgbdt44_5c0000gn/T/20180918-17591-23o4tm.bom -- /private/var/folders/ft/99qk4_9s0mb2pnhgbdt44_5c0000gn/T/d20180918-17591-1ojzgly/dmg.GpcrPQ /var/folders/ft/99qk4_9s0mb2pnhgbdt44_5c0000gn/T/d20180918-17591-129tris
diskutil eject /private/var/folders/ft/99qk4_9s0mb2pnhgbdt44_5c0000gn/T/d20180918-17591-1ojzgly/dmg.GpcrPQ
cp -pR /var/folders/ft/99qk4_9s0mb2pnhgbdt44_5c0000gn/T/d20180918-17591-129tris/.keychain_reauthorize/. /usr/local/Caskroom/google-chrome/69.0.3497.100/.keychain_reauthorize
cp -pR /var/folders/ft/99qk4_9s0mb2pnhgbdt44_5c0000gn/T/d20180918-17591-129tris/.keystone_install /usr/local/Caskroom/google-chrome/69.0.3497.100/.keystone_install
cp -pR /var/folders/ft/99qk4_9s0mb2pnhgbdt44_5c0000gn/T/d20180918-17591-129tris/Google\ Chrome.app/. /usr/local/Caskroom/google-chrome/69.0.3497.100/Google\ Chrome.app
==> Verifying Gatekeeper status of /Users/abk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/abk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
==> /Users/abk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg is not quarantined
==> Purging files for version 69.0.3497.100 of Cask google-chrome
Error: /Users/abk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg was not quarantined properly.
/usr/local/Homebrew/Library/Homebrew/cask/quarantine.rb:123:in `propagate'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:190:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:73:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.7.5-5-gccb08f1
==> macOS
10.13.6
==> SIP
Enabled
==> Java
1.8.0_131
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4041 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"

```

#### Output of `brew tap`

```
buo/cask-upgrade
homebrew/cask
homebrew/core
homebrew/services
```

**Comment by danielbayley** [comment]
This happens on a lot of casks I try to install now (seems to be on all casks with disk images `.dmg`s)… I first noticed it when I tried to install github-desktop, adding a `HOMEBREW_CASK_OPTS=--no-quarantine` environment variable seemed to fix it for a while, but now even that is failing when a `depends_on cask:` is used that relies on a `.dmg`.

**Comment by amyspark** [comment]
@alexbigkid : your log tells me that the quarantine attribute somehow disappears between the download and staging steps. As there are no errors logged, and `brew cask doctor` clearly states that your system can run Swift, I'd need to see what the script itself prints to console.

Please open a terminal, and run the script manually:

```
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/abk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg https://www.google.com/chrome/
```
Immediately after this,
```
echo $?
```
should return `0`. If not, please copy the return code and any console output here.

@danielbayley: if your `brew cask doctor` is similar to the OP's, please paste the full log of `brew cask install --debug` here.

Thanks in advance to both of you!

**Comment by oBattleTurtleo** [comment]
hi everyone, I have the same problem. hi amyspark here is my debug log

`brew cask install --debug google-chrome
Updating Homebrew...
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
Already downloaded: /Users/mrk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
==> Checking quarantine support
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/mrk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/mrk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
==> /Users/mrk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg is not quarantined
==> Quarantining /Users/mrk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/mrk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg https://www.google.com/chrome/
==> Downloaded to -> /Users/mrk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
==> Verifying SHA-256 checksum for Cask 'google-chrome'.
==> Installing Cask google-chrome
==> Cask::Installer#stage
hdiutil imageinfo /Users/mrk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/mrk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/c2/1xdsxvf965195g4bd3mppc700000gn/T/d20180922-24013-1mmgunn /Users/mrk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
find . -print0
mkbom -s -i /var/folders/c2/1xdsxvf965195g4bd3mppc700000gn/T/20180922-24013-bjyy6h.list -- /var/folders/c2/1xdsxvf965195g4bd3mppc700000gn/T/20180922-24013-h458t1.bom
ditto --bom /var/folders/c2/1xdsxvf965195g4bd3mppc700000gn/T/20180922-24013-h458t1.bom -- /private/var/folders/c2/1xdsxvf965195g4bd3mppc700000gn/T/d20180922-24013-1mmgunn/dmg.sdvNyI /var/folders/c2/1xdsxvf965195g4bd3mppc700000gn/T/d20180922-24013-c390zz
diskutil eject /private/var/folders/c2/1xdsxvf965195g4bd3mppc700000gn/T/d20180922-24013-1mmgunn/dmg.sdvNyI
cp -pR /var/folders/c2/1xdsxvf965195g4bd3mppc700000gn/T/d20180922-24013-c390zz/Google\ Chrome.app/. /usr/local/Caskroom/google-chrome/69.0.3497.100/Google\ Chrome.app
cp -pR /var/folders/c2/1xdsxvf965195g4bd3mppc700000gn/T/d20180922-24013-c390zz/.keystone_install /usr/local/Caskroom/google-chrome/69.0.3497.100/.keystone_install
cp -pR /var/folders/c2/1xdsxvf965195g4bd3mppc700000gn/T/d20180922-24013-c390zz/.keychain_reauthorize/. /usr/local/Caskroom/google-chrome/69.0.3497.100/.keychain_reauthorize
==> Verifying Gatekeeper status of /Users/mrk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/mrk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
==> /Users/mrk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg is not quarantined
==> Purging files for version 69.0.3497.100 of Cask google-chrome
Error: /Users/mrk/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg was not quarantined properly.
/usr/local/Homebrew/Library/Homebrew/cask/quarantine.rb:123:in `propagate'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:189:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:73:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'`

**Comment by amyspark** [comment]
So far I cannot reproduce this on Sierra.

@melmass, can you run this line in a Terminal and paste both *the output* and *exit code*?
```
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/imac/Library/Caches/Homebrew/downloads/90b87ef304c429d25069fecfb2f01425d03a0b66dfe2041520b1144e19557039--Astro-4135.dmg https://pexlabs-updates-xvuif5mcicazzducz2j2xy3lki.s3-us-west-2.amazonaws.com/Astro-4135.dmg https://www.helloastro.com/
```

**Comment by melMass** [comment]
The **swift** one returns:
 - No Output
 - `exit $?` returns `0`

The **xattr**:

```python
Traceback (most recent call last):
  File "/usr/bin/xattr-2.7", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

**Comment by danielbayley** [comment]
@amyspark Sorry, I have been busy! `google-chrome` cask actually just installed fine (with `HOMEBREW_CASK_OPTS=--no-quarantine` set in my `.zshenv`), but I am getting a _lot_ of `xattr` errors with other casks…

**Comment by vitorgalvao** [comment]
@danielbayley Installs that use `--no-quarantine` don’t help, because they don’t narrow the problem.

**Comment by melMass** [comment]
@amyspark  @danielbayley I can actually install any cask using `no-quarantine` forgot to mention. But disabling gatekeeper screws a lot of apps because they are being run  in App Translocation a macOS security mechanism for apps that are not properly installed.

**Comment by amyspark** [comment]
@melMass I've already fixed the translocation bug, but we haven't cut a stable version with the fix yet. About the Python bug - I'll add another integrity check to verify we have a working version of `xattr` before quarantining.

**Comment by melMass** [comment]
Not sure what you mean but I'm still not able to install casks after `brew update`

**Comment by amyspark** [comment]
@melMass We've already fixed the translocation bug in Homebrew/brew#4852; as for your `xattr` issue, Homebrew/brew#4990 disables quarantining if `xattr` doesn't work properly.

If you're still getting lease post an updated `brew cask doctor` and the stacktrace you get.

**Comment by amyspark** [comment]
Argh, I've deleted the branch without merging. I'll reopen.

**Comment by melMass** [comment]
I've just done that on another repo 🤒 ... 😃
