### ISSUE TITLE
Brew cask install google-chrome failed

### ISSUE THREAD

**Issue by ayush-ridecell** [Homebrew/homebrew-cask#90698]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

`brew cask install google-chrome` fails due to checksum mismatch error.
Running `brew install google-chrome` also fails due to checksum mismatch error.
Latest Version of chrome on Google - **86.0.4240.75**
The version being installed from brew after running the command `brew cask _stanza version google-chrome` - **85.0.4183.121**

**NOTE:** The issue persists even after running `brew update` and `brew update-reset` successfully followed by `brew cleanup -s` command before installing the google-chrome cask. I've also tried removing the cache by running `rm -rf "$(brew --cache)"` but nothing seems to fix this error.

**NOTE:** The issue has been occurring since the google-chrome version was updated to **86.0.4240.75**
#### Command that failed

```
brew cask install google-chrome
brew install google-chrome
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
==> Tapping homebrew/cask-versions
git clone https://github.com/Homebrew/homebrew-cask-versions /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions'...
Tapped 161 casks (208 files, 65.4MB).
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.5.5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/repos/Homebrew/homebrew-cask-versions --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --dump-header /private/tmp/github_api_headers20201012-13271-15ijast
git config --replace-all homebrew.private false
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.5.5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
==> Downloading https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.5.5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --header Accept-Language:\ en --retry 3 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.5.5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --header Accept-Language:\ en --fail --silent --retry 3 --location --remote-time --continue-at 0 --output /Users/vagrant/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg.incomplete https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/vagrant/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/vagrant/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
==> /Users/vagrant/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg is not quarantined
==> Quarantining /Users/vagrant/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/vagrant/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg https://www.google.com/chrome/
==> Downloaded to -> /Users/vagrant/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
tar tf /Users/vagrant/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
hdiutil imageinfo -format /Users/vagrant/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
Error: Checksum for Cask 'google-chrome' does not match.
Expected: b37980c7d92b589c062f748465a317af460ac29a0adde8e881e8ecd0b09a69a7
  Actual: 3ab76266189a7b2c5b9f789fbae7f7d25404e7158ee3e841dc0692eae2718182
    File: /Users/vagrant/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/HEAD/doc/reporting_bugs/checksum_does_not_match_error.md
/usr/local/Homebrew/Library/Homebrew/cask/verify.rb:26:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:168:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:68:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:93:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:73:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:72:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:72:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:37:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:95:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:186:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:14:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:191:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:191:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:14:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
==> Verifying SHA-256 checksum for Cask 'google-chrome'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
```

#### Output of `brew doctor --verbose`

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python
  node
Warning: Your Xcode (11.2.1) is outdated.
Please update to Xcode 11.3.1 (or delete it).
Xcode can be updated from the App Store.
```

#### Output of `brew tap`

```
==> Homebrew Version
2.5.5
==> macOS
10.14.6
==> SIP
Disabled
==> Java
11.0.8, 1.8.0_222
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3672 casks)
/usr/local/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk (43 casks)
/usr/local/Homebrew/Library/Taps/wix/homebrew-brew (1 cask)
```

**Comment by eenick** [comment]
Submitted pull request to Chrome 86.0.4240.80. Cask has been fixed. The show must go on! #90746

**Comment by ayush-ridecell** [comment]
@eenick Thanks for the update 👍 
But when I ran the `brew update` command followed by `brew install google-chrome`, I still get the SHA mismatch error.
I ran `brew cask _stanza version google-chrome` and it's giving me chrome version **85.0.4183.121** instead of the latest version **86.0.4240.80**

**Comment by miccal** [comment]
Issue being investigated in https://github.com/Homebrew/homebrew-cask/issues/90593.

**Comment by maxim-lobanov** [comment]
Hello everyone!
@miccal , @miccal ,

How much time does updating `google-chrome` formula take usually? Is it possible to speed up such updates somehow?
We use `brew cask install google-chrome` as a part of our image-generation CI and we often have problems with `google-chrome` installation because every time when new version is released, `cask install` is broken until PR with updated check sum is merged

**Comment by miccal** [comment]
@maxim-lobanov it depends on how quickly someone submits a PR to update `google-chrome`; PR's are not automated, we rely on contributors to submit them.

**Comment by maxim-lobanov** [comment]
Does it make sense to remove hash-sum at all from formula? With the current approach, formula looks useless because can be broken any moment of time.
I can't find any flag in brew to ignore checksum validation during installation.

**Comment by miccal** [comment]
> Does it make sense to remove hash-sum at all from formula?

No, the Cask has an `appcast` and therefore requires a `version` and `sha256`.

> With the current approach, formula looks useless because can be broken any moment of time.

True, it will be broken when it requires updating and someone then needs to submit a PR to update it.

> I can't find any flag in brew to ignore checksum validation during installation.

There is no such flag.

If the current way that the `google-chrome` cask is maintained is not suitable for your use-case, I would suggest hosting one [in your own tap.](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap)
